language: node_js

node_js:
- '6'

addons:
  apt:
    sources:
    - heroku
    packages:
    - heroku-toolbelt
        
install:
- npm install

script: true

before_deploy:
- cat .netrc >> $HOME/.netrc
- chmod 0600 /home/travis/.netrc
- heroku apps
- heroku apps | grep -q travis-ci-rnovosad-$TRAVIS_BRANCH || heroku apps:create travis-ci-rnovosad-$TRAVIS_BRANCH
- heroku git:remote -a travis-ci-rnovosad-$TRAVIS_BRANCH

deploy:
  provider: heroku
  api_key: d97cd3db-face-4c9e-897c-7e074c2dac5a
  app: travis-ci-rnovosad-$TRAVIS_BRANCH
  on: $TRAVIS_BRANCH

after_deploy:
- ./node_modules/.bin/wdio wdio.conf || travis_terminate 1
